module.exports = [
  'function mint(uint mintAmount) external returns (uint)',
  'function redeemUnderlying(uint redeemAmount) external returns (uint)',
  'function _setImplementation(address implementation_, bool allowResign, bytes memory becomeImplementationData) external',
  'function name() external view returns (string)',
  'function symbol() external view returns (string)',
  'function decimals() external view returns (uint8)',
  'function admin() external view returns (address)',
  'function balanceOf(address account) external view returns (uint)',
  'function pendingAdmin() external view returns (address)',
  'function comptroller() external view returns (address)',
  'function interestRateModel() external view returns (address)',
  'function getAccountSnapshot(address account) external view returns (uint, uint, uint, uint)',
  'function borrowRatePerBlock() external view returns (uint)',
  'function supplyRatePerBlock() external view returns (uint)',
  'function exchangeRateStored() external view returns (uint)',
  'function reserveFactorMantissa() external view returns (uint)',
  'function accrualBlockNumber() external view returns (uint)',
  'function borrowIndex() external view returns (uint)',
  'function totalBorrows() external view returns (uint)',
  'function totalReserves() external view returns (uint)',
  'function totalSupply() external view returns (uint)',
  'function underlying() external view returns (address)',
  'function implementation() external view returns (address)',
  'function internalCash() external view returns (uint)',
  'function totalCollateralTokens() external view returns (uint)',
  'function collateralCap() external view returns (uint)',
  'function _setCollateralCap(uint newCollateralCap) external',
  'function accountCollateralTokens(address account) external view returns (uint)'
];
